Withdraw extension
0xflair/evm-contracts pull request #18
Opened 2022-07-18 10:12 UTC by kasrakhosravi

## Description:

> Tell us about your change

## PR Checklist
- [ ] :eyes: I have self-reviewed my PR, leaving comments on any changes which may trigger a discussion
- [ ] :pencil2: Added relevant tests

2022-07-18 10:20 UTC, aramalipoor commented on contracts/common/WithdrawExtension.sol
> +        require(!proceedsRecipientLocked, "Common/RECIPIENT_LOCKED");
```suggestion
        require(!proceedsRecipientLocked, "WITHDRAW/RECIPIENT_LOCKED");
```

2022-07-18 10:22 UTC, aramalipoor commented on contracts/common/WithdrawExtension.sol
> +    function lockProceedsRecipient() external;
Probably better to use more generic name, like `setWithdrawRecipient` and `lockWithdrawRecipient`

2022-07-18 10:22 UTC, aramalipoor commented on contracts/streams/ERC721/presets/ERC721EqualEmissionStream.sol
> +    WithdrawExtension
Let's also update the ERC721 presets to use this extension and remove the "proceeds" extension from collections 🚀

2022-07-19 08:51 UTC, aramalipoor commented on contracts/common/WithdrawExtension.sol
> +    }
It's repeated, can be removed

2022-07-19 11:52 UTC, kasrakhosravi commented on contracts/common/WithdrawExtension.sol
> +    }
you mean remove `__EmergencyOwnerWithdrawExtension_init()` and replace it with `__WithdrawExtension_init`? In that case the recipient has to be passed to the `__WithdrawExtension_init`

2022-07-19 13:13 UTC, aramalipoor commented on contracts/common/WithdrawExtension.sol
> +    }
Yep that's correct, we only need one initializer, with same name as contract

2022-07-25 07:26 UTC, aramalipoor commented on contracts/common/WithdrawExtension.sol
> +            return true;
We need to either "revert" from this method, or return a boolean.

I'd suggest to revert, which means:
- if we want to allow just `return;`
- if we want to check a condition `require(condition, reason)`...
- if we want to revert `revert(reason)`

2022-07-25 07:34 UTC, aramalipoor requested changes
To make the assert function to only revert if sender shouldn't withdraw, no return value needed.

2022-07-25 11:56 UTC, aramalipoor approved these changes

2022-07-25 12:04 UTC, merged